apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run:  {{ .Values.wordpress }}
  name:  {{ .Values.service_name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort:  {{ .Values.node_port_no }}
  selector:
    run: {{ .Values.wordpress }}
  type: NodePort
status:
  loadBalancer: {}
